<#

CopyLeft SVET :)

NAME
	Create a .zip Archive with an Optimal Compression - 2
	
SYNOPSIS
	

SYNTAX
	
	
DESCRIPTION
	
	
PARAMETERS
	
	
INPUTS
	
	
OUTPUTS
	
	
NOTES
	
	
EXAMPLES
	
	
RELATED LINKS
	
	
#>


$d = Get-Date -Format "dddd-MM-dd-yyyy"
Compress-Archive -LiteralPath ".\outlook.pst" -DestinationPath ".\$d.outlook.zip" -CompressionLevel Optimal -Force -Verbose


# SIG # Begin signature block
# MIIFagYJKoZIhvcNAQcCoIIFWzCCBVcCAQExCzAJBgUrDgMCGgUAMGkGCisGAQQB
# gjcCAQSgWzBZMDQGCisGAQQBgjcCAR4wJgIDAQAABBAfzDtgWUsITrck0sYpfvNR
# AgEAAgEAAgEAAgEAAgEAMCEwCQYFKw4DAhoFAAQUrFFE2vOL/OAQrfL240TNhi2P
# OdugggMGMIIDAjCCAeqgAwIBAgIQJLzUFQ0UMqZIQD0LynYJzzANBgkqhkiG9w0B
# AQsFADAZMRcwFQYDVQQDDA5HbyBMaXZlIFVLIEx0ZDAeFw0yMjA3MTYxMTU3MzZa
# Fw0yNzA3MTUyMTAwMDBaMBkxFzAVBgNVBAMMDkdvIExpdmUgVUsgTHRkMIIBIjAN
# BgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1jBbQhei1OZxT2X07woTaSXAAIhc
# nY1a8OwQdzKLpWKCskGbDmGBH0bdqLq1m+y8jWKnf1tEnzaFVxUKrcwq57hy8og2
# xK9Ciq2+X43ZpA4acLUnvK0auUNig2vwWXlnPr4vh4g6+E6nMvvyhPA5ND+Uvhm2
# wSi7Z+qlmYQqm7wI7IEoaGy/8zyPB1vnWOL2UUYL8oTSklGdA6/wPGcV0S41vfGR
# 1YClE/AaAMB2+GZgkGgw9gQvKwsNRFIJSKu3OHICfrPRJgObdMnKr6F2jFl2LP+E
# Rf/Qy7BkTMwLIuxm2Tik+yPh3ZLGWGr2TtQoipNcdIg/7jmGuepTssD5/QIDAQAB
# o0YwRDAOBgNVHQ8BAf8EBAMCB4AwEwYDVR0lBAwwCgYIKwYBBQUHAwMwHQYDVR0O
# BBYEFDBp69/PtsKtexPQHwwNhwtX73JqMA0GCSqGSIb3DQEBCwUAA4IBAQBQ4+Qm
# FQd/u421ZKpspyhsYw/Hjnn27uBwJ1420lpQSApuI6BnsmlZlpNVAl5ETMtbzezo
# x4xwkQ2H4/+FWg4/Mic0adMwAgqGEeOpWYZxpUQFnzCIlyH6QmXvDLuR5FwVUFKt
# fdbUj5waOOY6UJ3MSGWEykAX3R3jF/g9AgZmfvTeK9ko72QU595uIHRRXubq3akk
# 8WGiZcvgZ6WwzbHDw3iM3Q16OKOGKC/UQgJ1eiawavJUF7DQawB1VonfnbT9caZB
# 8H88Qf8u3g2FQlStoZ1lYfIUj37PZfbaBhVVZyMS7FxmSmfLXvQLtV0pT7nSRK63
# Ki30MG53JtJQdqYmMYIBzjCCAcoCAQEwLTAZMRcwFQYDVQQDDA5HbyBMaXZlIFVL
# IEx0ZAIQJLzUFQ0UMqZIQD0LynYJzzAJBgUrDgMCGgUAoHgwGAYKKwYBBAGCNwIB
# DDEKMAigAoAAoQKAADAZBgkqhkiG9w0BCQMxDAYKKwYBBAGCNwIBBDAcBgorBgEE
# AYI3AgELMQ4wDAYKKwYBBAGCNwIBFTAjBgkqhkiG9w0BCQQxFgQUZZnA0z3NQcz/
# YSlbWDbgi2VT7kUwDQYJKoZIhvcNAQEBBQAEggEAUpx7Ky+y5RM5DyUUR8L2yrok
# tAhTIsOUJuBEt/DqZSAGuPE+tXG/TGZTUV3yXkLEGPY71UOnqMdqzZBxU2NlVip+
# /31Ot2cRVIBWwo4mncuupDDGTAeAh3jxJqsm2UBt8HhkIy+raapW2cMFrzOBP0VH
# yfgy06NQ75Ry8jZupXBcD3e7HuVGn6XZLfy+FWFJISARirRCgTQZWcf1TjptlbcX
# bLcN2w3IeL1vlRdJS4TQEnr7pHB32q3xX30NtYTM2visl3Vt4vp4XPV4M55SpFUn
# yABC3dOnN8ofVZyu1Y1x6TAUpe41u/1t3FVCd8gQfO5FJfaoKqvug1cRPgLGiw==
# SIG # End signature block
