<#

CopyLeft SVET :)

NAME
	Update a Current .zip Archive via 7z Commands
	
SYNOPSIS
	

SYNTAX
	
	
DESCRIPTION
	
	
PARAMETERS
	
	
INPUTS
	
	
OUTPUTS
	
	
NOTES
	
	
EXAMPLES
	
	
RELATED LINKS
	
	
#>

"C:\Program Files\7-Zip\7z" u "C:\tmp\archive.zip" "M:\Ethical Hacking\3 SCANNING & ENUMERATION\*.*"



# SIG # Begin signature block
# MIIFagYJKoZIhvcNAQcCoIIFWzCCBVcCAQExCzAJBgUrDgMCGgUAMGkGCisGAQQB
# gjcCAQSgWzBZMDQGCisGAQQBgjcCAR4wJgIDAQAABBAfzDtgWUsITrck0sYpfvNR
# AgEAAgEAAgEAAgEAAgEAMCEwCQYFKw4DAhoFAAQUHH/FtD873PKC2lNl+NjzEKim
# u1KgggMGMIIDAjCCAeqgAwIBAgIQEtSZ1T/kOptFn60oc6QVGTANBgkqhkiG9w0B
# AQsFADAZMRcwFQYDVQQDDA5HbyBMaXZlIFVLIEx0ZDAeFw0yMjA3MTYxMTU4MDRa
# Fw0yNzA3MTUyMTAwMDBaMBkxFzAVBgNVBAMMDkdvIExpdmUgVUsgTHRkMIIBIjAN
# BgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA6sGeW+q3SYpKYZDPQu7JlI3+EWSP
# CoyXoSwzgC1SpE6vkEJYv0A4INSi4qRpiZhx7bxEREB9nDEWZTLhnXj55xe/0f6Z
# 1Xvszi9AZb0S7Hs9rIdPOYI0+FCLLauKShC7re2Gb7Yneh1GOnyLBzilj4tf2NIL
# SgaVBSS1UOH50i+MXwsBBjtGuIX8mipoGFXz2KQB7RLg0f8B4fM17X/to9/Mvh64
# LkJ641g9YbfG8hMyV49GgtOamJ8Vs0hc5M5k2T01Xen1ohDH7CT7N2MJ8DZdHWyE
# T7HCc3DFihGiELCDTL8mSeCW/9y0IZfGe/wXjswN5lumVkmgdyuAW8FEWQIDAQAB
# o0YwRDAOBgNVHQ8BAf8EBAMCB4AwEwYDVR0lBAwwCgYIKwYBBQUHAwMwHQYDVR0O
# BBYEFFqWiQL2Ulc7dX4k9KFaUxF615mlMA0GCSqGSIb3DQEBCwUAA4IBAQBVBIBh
# s++k7Fe4+xqRc5N23lLDBw0+3htnzaFSxHh5geyMH9A5kDyGzcn1JpmeTyWPgdnN
# ecuL+Pu3GGPGfVP43G9Pb/E1hlh05zDbkqZK7SdxYE3hpjC+RbVoRQu0nrpDhL/x
# CNwt/WJt7eWT4Z+YRXZSPQMCa3JAMuQoZS9/q5F6npJsoErntRX//x/K6eOCff9I
# C+txUCaBrPIdjv5nuXqJb96L2zgUsUjg9XOAhPclu+Kl+NGgJF8hk+MyqB+fitkR
# pKe1GngOZqVCwTzLx56p67b7anhHn1XzNCAewcDjB3miPVR7vYN4ge1T4DBJpI5r
# bzHQtincz/LM9nLnMYIBzjCCAcoCAQEwLTAZMRcwFQYDVQQDDA5HbyBMaXZlIFVL
# IEx0ZAIQEtSZ1T/kOptFn60oc6QVGTAJBgUrDgMCGgUAoHgwGAYKKwYBBAGCNwIB
# DDEKMAigAoAAoQKAADAZBgkqhkiG9w0BCQMxDAYKKwYBBAGCNwIBBDAcBgorBgEE
# AYI3AgELMQ4wDAYKKwYBBAGCNwIBFTAjBgkqhkiG9w0BCQQxFgQUnpmYFBuOMjml
# wa0Eqk1IC4zcXR4wDQYJKoZIhvcNAQEBBQAEggEAFuTZ87hfCRcztiRvALt/4PUV
# KvxHXIdW/Cn594UNCQpj7ZlQsKQ11Z6wiGYakrjTeb6yhd1Tej0j3gyOm/fMsoo8
# f6UuFhnNo/RMP7fIlfLhncvK9tzjiKHdSQyCtXaeUvRwwQDToEDjh9GPD/7EH8eb
# HbuOy1JGHtoiJdlav456cz6xk/7k6m8WkBft9Fp5VtBed39fHyD9x+wOVCxDkIsI
# F7Q+B+sjX5UzLxMcvCR4XUPzPpDDlQYzd3nGp5KkzXqpvHdWT2OB5w+VJGrNayWx
# He+OBpRGMO1Msa5CcxGpxrCQ3hGeYOgPthJRHcQl653+k1NNtZnCT5yi+IYqxw==
# SIG # End signature block
